name: Update Weather Information

on:
  schedule:
    - cron: "0 * * * *"  # Cập nhật mỗi giờ
  workflow_dispatch:  # Cho phép chạy thủ công

jobs:
  update-weather:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install requests
        run: |
          pip install requests

      - name: Fetch weather data
        run: |
          python update_weather.py

      - name: Commit updated README
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update weather information"
          git push
